### ISSUE TITLE
Enable PHP's pcntl extension

### ISSUE THREAD

**Issue by kukukk** [LynxSolutions/php-docker#2]
It seems that the missing pcntl extension can cause some issues: https://github.com/laravel/pail/issues/43
It is also suggested by Laravel: https://github.com/laravel/framework/blob/11.x/composer.json#L172
Wouldn't be better to include it?

**Comment by bogdannbv** [comment]
Even though I'm yet to encounter this issue, I've made a PR( #3 ) to add it, please review it :grin:
